[Tagページ最終課題]一部エラー
shinonome-inc/qiita_client_yukiy pull request #13
Opened 2023-03-10 05:34 UTC by Yuki0316

2023-03-10 09:20 UTC, mcz9mm commented on lib/services/qiita_client.dart
> +        'https://qiita.com//api/v2/tags/$tagName/items?page=$pageNumber&page=1&per_page=20';
せっかく`page=$pageNumber`定義してるのに`&page=1`これのせいで、、

2023-03-10 09:20 UTC, mcz9mm commented on lib/pages/tag_detail_list_page.dart
> +              listTagDetail = snapshot.data!;
毎回20件しか表示されないのは
Listに対してaddするのではなく、プロパティごと値を書き換えてるから。

こんな感じにしてあげるとシンプルになるよ。

```
  Future<void> _fetchTagData() async {
    _isLoading = true;
    futureTagDetails = QiitaClient.fetchTagDetail(widget.tagName!, pageNumber);
  }

~~~~~~~~
            if (snapshot.connectionState == ConnectionState.done &&
                _isLoading) {
              _isLoading = false;
              pageNumber += 1;
              listTagDetail.addAll(snapshot.data!);
            }
            if (snapshot.hasData) {
              return ArticleListView(
                articles: listTagDetail,
                scrollController: _scrollController,
                itemCount: _isLoading
                    ? listTagDetail.length + 1
                    : listTagDetail.length,
              );
            } 
```

2023-03-11 02:45 UTC, Yuki0316 commented on lib/pages/tag_detail_list_page.dart
> +              listTagDetail = snapshot.data!;
futureBuilder内、fetchData内のコードをアドバイス通り簡潔化し、不要だと思われるコードを削除したところ、下記の通り動作できました！

https://user-images.githubusercontent.com/102783724/224460843-c6965535-7c8d-466f-91e3-549123e8f85f.mp4

print文の位置も調整しました。
<img width="586" alt="スクリーンショット 2023-03-11 11 42 20" src="https://user-images.githubusercontent.com/102783724/224460861-e1eb0b0b-9f02-4b13-9c3b-8d8a497cf177.png">

2023-03-11 02:46 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +        'https://qiita.com//api/v2/tags/$tagName/items?page=$pageNumber&page=1&per_page=20';
余分な"$page=1"を削除しました。完全に見落としていました…

2023-03-18 01:58 UTC, KobayashiYoh requested changes
コメントしました。

2023-03-18 01:58 UTC, KobayashiYoh commented on lib/ui_components/article_list_view.dart
> +              listTile(article, context),
詳しくはfigmaを見ていただきたいのですが、FeedPageで「投稿記事」のテキストは表示しないようにしましょう。

2023-03-18 01:58 UTC, KobayashiYoh commented on lib/ui_components/tag_grid_view_cell.dart
> +  // }
不要なコメントアウトは削除した方がいいかもしれませんね。

2023-03-18 01:58 UTC, KobayashiYoh commented on lib/ui_components/tag_grid_view_cell.dart
> +                  ),
画像のキャッシュ化とエラー処理までできていて素晴らしいです👍

2023-03-18 01:58 UTC, KobayashiYoh commented on lib/ui_components/tag_grid_view.dart
> +      ],
ここの_loadingView削除し忘れていますね。
ColumnとExpandedと一緒に削除した方がいいかもしれませんね。

2023-03-18 02:27 UTC, Yuki0316 commented on lib/ui_components/article_list_view.dart
> +              listTile(article, context),
bool値によってFeedPageとTag詳細ページの「投稿記事」を切り替えました！

2023-03-18 02:32 UTC, Yuki0316 commented on lib/ui_components/tag_grid_view.dart
> +      ],
不要な箇所を削除しました！

2023-03-18 02:32 UTC, Yuki0316 commented on lib/ui_components/tag_grid_view_cell.dart
> +  // }
不要なコメントアウトを削除しました！

2023-03-18 02:33 UTC, Yuki0316 commented on lib/ui_components/tag_grid_view_cell.dart
> +                  ),
ありがとうございます🙇

2023-03-18 02:39 UTC, KobayashiYoh commented
LGTMです👍
二次レビューに進んでください！

2023-03-18 02:39 UTC, KobayashiYoh approved these changes

2023-03-18 09:17 UTC, mcz9mm commented
LGTM

2023-03-18 09:17 UTC, mcz9mm approved these changes

2023-03-18 09:17 UTC, merged