Feature/authorization function
shinonome-inc/qiita_client_yukiy pull request #19
Opened 2023-07-08 01:56 UTC by Yuki0316

## 概要

## CLIENT_IDとCLIENT_SECRET
https://drive.google.com/drive/folders/1VCIxGsXi2GFxFAxsP5GyNvWNnzs36C17
プロジェクト直下に配置してください。
<img width="250" alt="スクリーンショット 2023-07-08 10 54 45" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/dd6b779f-8342-4259-b157-15723db82734">

## 実装した内容

## UI

## 動作確認

## 参考

## その他

2023-07-08 01:57 UTC, KobayashiYoh commented
`ios/Podfile`にこれを使ってみてください。
```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

2023-07-08 02:18 UTC, KobayashiYoh commented
```lock
PODS:
  - Flutter (1.0.0)
  - FMDB (2.7.5):
    - FMDB/standard (= 2.7.5)
  - FMDB/standard (2.7.5)
  - path_provider_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - shared_preferences_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - sqflite (0.0.3):
    - Flutter
    - FMDB (>= 2.7.5)
  - webview_flutter_wkwebview (0.0.1):
    - Flutter

DEPENDENCIES:
  - Flutter (from `Flutter`)
  - path_provider_foundation (from `.symlinks/plugins/path_provider_foundation/ios`)
  - shared_preferences_foundation (from `.symlinks/plugins/shared_preferences_foundation/ios`)
  - sqflite (from `.symlinks/plugins/sqflite/ios`)
  - webview_flutter_wkwebview (from `.symlinks/plugins/webview_flutter_wkwebview/ios`)

SPEC REPOS:
  trunk:
    - FMDB

EXTERNAL SOURCES:
  Flutter:
    :path: Flutter
  path_provider_foundation:
    :path: ".symlinks/plugins/path_provider_foundation/ios"
  shared_preferences_foundation:
    :path: ".symlinks/plugins/shared_preferences_foundation/ios"
  sqflite:
    :path: ".symlinks/plugins/sqflite/ios"
  webview_flutter_wkwebview:
    :path: ".symlinks/plugins/webview_flutter_wkwebview/ios"

SPEC CHECKSUMS:
  Flutter: f04841e97a9d0b0a8025694d0796dd46242b2854
  FMDB: 2ce00b547f966261cd18927a3ddb07cb6f3db82a
  path_provider_foundation: eaf5b3e458fc0e5fbb9940fb09980e853fe058b8
  shared_preferences_foundation: 5b919d13b803cadd15ed2dc053125c68730e5126
  sqflite: 31f7eba61e3074736dff8807a9b41581e4f7f15a
  webview_flutter_wkwebview: b7e70ef1ddded7e69c796c7390ee74180182971f

PODFILE CHECKSUM: 7368163408c647b7eb699d0d788ba6718e18fb8d

COCOAPODS: 1.11.3

```

2023-07-30 23:41 UTC, MiyuSato commented
認証は問題なく動いています！
まず、MyPageの認証したユーザーの情報表示について、投稿記事がYukiさんのものになったままなので修正お願いします

<img width="565" alt="スクリーンショット 2023-07-31 8 37 12" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/83227352/977ef697-da31-445a-9639-9d1b09b24945">

2023-07-30 23:47 UTC, MiyuSato commented
スワイプしてログイン画面に戻れてしまうので、戻れないように修正お願いします。
動画のように意図しない動作が起きてしまいます。

https://github.com/shinonome-inc/qiita_client_yukiy/assets/83227352/68959b13-c76b-4246-8828-62f3695d31d1

2023-08-01 01:43 UTC, Yuki0316 commented
> スワイプしてログイン画面に戻れてしまうので、戻れないように修正お願いします。
> 
>  2023-07-31.8.43.58.mov

個人的に簡単そうだったので、こちらから修正を行いました！[c247021](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/c24702103c79f72bf626920d9a625094ce06a47d)

2023-08-02 12:30 UTC, Yuki0316 commented
> 認証は問題なく動いています！ まず、MyPageの認証したユーザーの情報表示について、投稿記事がYukiさんのものになったままなので修正お願いします
> 
> <img alt="スクリーンショット 2023-07-31 8 37 12" width="400" src="https://user-images.githubusercontent.com/83227352/257081259-977ef697-da31-445a-9639-9d1b09b24945.png">

投稿記事のtokenを見直したところ、不備がありましたので変更を行いました。サブアカウントを作成し実行したところ、以下の画像の通り修正できました。

<img src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/6247c52b-8086-4417-8a89-32a61f42a9cf" width="300">

2023-08-03 02:10 UTC, KobayashiYoh requested changes
13点コメントしました。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +    });
これだと未ログイン時も`getAccessToken`メソッドが実行され、アクセストークンを発行しようとして401エラーが返されてしまいますね。
また、適切に状態管理が行われていないため、401エラーが返された後もローディングが表示され続けています。
<img width="1440" alt="スクリーンショット 2023-08-03 9 27 58" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/82624334/3d23a75c-cf6a-4fd6-8772-2116bb5e4aef">

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +  }
全ての画面にこの条件分岐を書いていくのは大変かつコードの可読性も下がってしまうため、画面遷移の方法を工夫してスワイプバックができなくなるようにした方がいいかもしれませんね。
修正は任意です。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/top_page.dart
> +                      context: context,
背景が透明になっているため、記事の読み込みが終わるまでヘッダーだけが表示されています。
この場合、背景色は透明より白の方が良いと思われます。
<img width="300" alt="スクリーンショット 2023-08-03 9 35 13" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/82624334/cf54c254-92f1-42d7-bc3c-b816efdf91f2">

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +  }
不要な関数は削除しましょう。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +
isLoadingには既にtrueという値が代入されて初期化されているため、lateは不要ですね。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +    print('pageNumber is $pageNumber');
不要な待ち時間は削減しましょう。
1秒待ち時間が減るだけでアプリの使いやすさはぐっと高まると思います。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +      setState(
至る所にif(mounted)が見受けられますが、これってどういった意図がありますか？

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +                    return Container();
snapshotの値を使わないのであれば、FutureBuilderを使用する必要はないかもしれないですね。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +    final authorization = {"Authorization": "Bearer $token"};
アクセストークンを.envファイルに記述するのはするのは一般的ではないですね。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +        'https://qiita.com//api/v2/oauth/authorize?client_id=67b56264308408ab81df90f81184e680ffa26d48&scope=read_qiita+write_qiita&state=bb17785d811bb1913ef54b0a7657de780defaa2d';
cliend_idはGitの差分に入れないでください。
必ずenvファイルから読み取ったものを利用するようにしてください。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/ui_components/article_list_view.dart
> +        );
同じようなDividerを2箇所で別々に定義するのではなく、DivierはlistTileの中に定義した方が良いですね。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/ui_components/my_page_introduction.dart
> +  return Column(
myIntroductionメソッドは定義せず、buildメソッド内に記述してしまう方が適切ですね。

2023-08-03 02:10 UTC, KobayashiYoh commented on lib/ui_components/article_list_view.dart
>        title: Text(
発想が天才ですね💡

2023-08-05 01:31 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +    });
FeedPageでのinitStateの処理を適切な書き方に変更しました。また、FeedPageはログイン時でも未ログイン時でも記事を表示できるように処理を変更しました。

2023-08-05 02:44 UTC, Yuki0316 commented on lib/pages/user_page.dart
> +      setState(
tagPageのif(mounted)のみ、削除したところ、[こちら](https://blog.mrym.tv/2019/12/traps-on-calling-setstate-inside-initstate/)のページのエラーが発生したため残しておきました。
他のページでは消しても問題なかった為、削除しておきました！

2023-08-05 03:48 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +  }
条件分岐を削除し、未ログイン時とログイン時両方で、スワイプバックができないように変更しました！こちらの変更はFeedPageとTagPageで行いました。

2023-08-05 04:06 UTC, Yuki0316 commented on lib/pages/top_page.dart
> +                      context: context,
modalの背景色をwhiteに変更しました。
[modalの背景色変更](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/f04364904b92ebda65f6ce0c2d393ee60b743876)

2023-08-05 04:07 UTC, Yuki0316 commented on lib/pages/user_page.dart
> +  }
不要な関数を削除しました！
[4ea45e8](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/4ea45e80f3b5d42c4f3a2d4a075bfd73ff910170)

2023-08-05 04:09 UTC, Yuki0316 commented on lib/pages/user_page.dart
> +
不要なlateを削除しました！[不要なlateの削除](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/aa1e34499811cf45d0aa223910928166f63c4887)

2023-08-06 00:09 UTC, Yuki0316 commented on lib/pages/user_page.dart
> +    print('pageNumber is $pageNumber');
不要なFuture.delayedを削除しました！

2023-08-06 00:12 UTC, Yuki0316 commented on lib/pages/user_page.dart
> +                    return Container();
<img width="693" alt="スクリーンショット 2023-08-06 9 11 33" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/a290d7dc-9531-4a33-9df6-3f3a05e7878e">
ArticleListViewのarticlesの中身をsnapshot.dataに書き換えました。

2023-08-06 00:16 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +    final authorization = {"Authorization": "Bearer $token"};
無限ローディング修正の際に、List<article>を認証済みかどうかに関わらず、データを取れるように書き換えたため、上記のアクセストークンの記述を削除しました。また、アクセストークンは.envファイルに記述するのは一般的でないと理解したため、他の場所の同じようなコードもまとめて書き換えました。
[無限ローディングの修正](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/f5c13bcfbe6dd8ce5a745cbaff28354fa779db48)

2023-08-06 00:20 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +        'https://qiita.com//api/v2/oauth/authorize?client_id=67b56264308408ab81df90f81184e680ffa26d48&scope=read_qiita+write_qiita&state=bb17785d811bb1913ef54b0a7657de780defaa2d';
envから読み取ったclient_idの変数に書き換えました！[clientIDをenvから読み取り](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/f49e2296c6ff9d429ecbbda94208ee5d7e4616e2)

2023-08-06 00:41 UTC, Yuki0316 commented on lib/ui_components/article_list_view.dart
> +        );
Dividerをlisttileに入れる方法が分からなかったため、build関数内に変更を加え、dividerを一箇所にまとめました。[Dividerを一箇所にまとめる](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/116f436f40861f3dc726024ab5dc21ab46ec4e8e)

2023-08-06 00:56 UTC, Yuki0316 commented on lib/ui_components/my_page_introduction.dart
> +  return Column(
メソッドを削除し、buildメソット内に移植しました！さらに不必要な変数を削除しました。[myPageIntroductionコードの改善](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/7aa9051345dcc4d867ce99deb9c0c07afdf4897e)

2023-08-06 00:56 UTC, Yuki0316 commented on lib/ui_components/article_list_view.dart
>        title: Text(
ありがとうございます！

2023-08-06 01:06 UTC, Yuki0316 commented on lib/pages/top_page.dart
> +                      context: context,
FeedPageやその他記事ページのモーダルの背景も透明になっていたため、ArticleLsitView内でモーダルの背景色を白に変更しました！[modalBottomSheetの背景色を全て白に変更](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/7c51ec5bfaa9a2c7801989faba51ad4a4565bda1)

2023-08-10 04:43 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +    });
OKです。

2023-08-10 04:43 UTC, KobayashiYoh commented on lib/pages/top_page.dart
> +                      context: context,
OKです。

2023-08-10 04:43 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +  }
OKです。

2023-08-10 04:43 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +  }
OKです。

2023-08-10 04:43 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +
OKです。

2023-08-10 04:43 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +    print('pageNumber is $pageNumber');
OKです。

2023-08-10 04:44 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +      setState(
良いですね👍

2023-08-10 04:44 UTC, KobayashiYoh commented on lib/pages/user_page.dart
> +                    return Container();
OKです。

2023-08-10 04:44 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +    final authorization = {"Authorization": "Bearer $token"};
OKです。

2023-08-10 04:45 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +        'https://qiita.com//api/v2/oauth/authorize?client_id=67b56264308408ab81df90f81184e680ffa26d48&scope=read_qiita+write_qiita&state=bb17785d811bb1913ef54b0a7657de780defaa2d';
OKです。

2023-08-10 04:46 UTC, KobayashiYoh commented on lib/ui_components/my_page_introduction.dart
> +  return Column(
OKです。
不要なものは削除していきましょう👍

2023-08-10 08:43 UTC, KobayashiYoh requested changes
修正お疲れ様です。
追加で5点コメントしたのでご確認お願いします🙏

2023-08-10 08:43 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +    // });
不要な処理はコメントアウトではなく、削除しておきましょう。

2023-08-10 08:43 UTC, KobayashiYoh commented on lib/pages/web_view_screen.dart
> +                        ),
TopPageのbuildメソッド内で既にWillPopScopeが定義されているため、こちらのWillPopScopeは不要ですね。

2023-08-10 08:43 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +  }
扱うのはAPIキーではなくアクセストークンなので、文字列は`"api_key"`じゃない方がいいかもです。

2023-08-10 08:43 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +  }
クライアントIDやクライアントシークレットと同様に、stateの値もGitの差分に入れない方が良いですね。

2023-08-10 08:43 UTC, KobayashiYoh commented on lib/ui_components/search_bar.dart
> +  const QiitaSearchBar({Key? key, required this.textField}) : super(key: key);
ファイル名も忘れずに変更しておきましょう。

2023-08-13 00:20 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +    // });
不要なコメントアウトを削除しました。

2023-08-13 00:21 UTC, Yuki0316 commented on lib/pages/web_view_screen.dart
> +                        ),
不要なWillPopScopeを削除しました！

2023-08-13 00:21 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +  }
文字列をtokenに変更しました！[文字列の変更](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/6b4472598473de981940051cb6dbf084e3b412eb)

2023-08-13 01:07 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +  const QiitaSearchBar({Key? key, required this.textField}) : super(key: key);
ファイル名も同様変更しました！[ファイル名の変更、stateを変数に変更](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/bd6bdb23b4c13d1585eefc4a4820c894d5eb0c06)

2023-08-13 01:20 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +  }
こちらstateの値をgitの差分に入れないよう修正したのですが、下記画像のurlにstate=nullと出てきます。動作には問題ないようなのですが、こちら要修正でしょうか？？
<img width="647" alt="スクリーンショット 2023-08-13 10 15 48" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/2126bac0-9fa1-4715-8a11-7e465e29f6ee">


https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/0a731788-f1c7-4307-8859-07e1d3a9efc1

2023-08-16 12:13 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +    // });
OKです。

2023-08-16 12:14 UTC, KobayashiYoh commented on lib/pages/web_view_screen.dart
> +                        ),
OKです。

2023-08-16 12:15 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +  }
いいですね👍

2023-08-16 12:16 UTC, KobayashiYoh commented on lib/services/qiita_client.dart
> +    final String? state = uri.queryParameters["state"];
先ほど口頭で説明させていただきましたが、この変数uriにはstateが含まれていないため、変数stateがnullになってしまいます。

2023-08-16 12:17 UTC, KobayashiYoh commented on lib/ui_components/search_bar.dart
> +  const QiitaSearchBar({Key? key, required this.textField}) : super(key: key);
OKです。

2023-08-16 12:18 UTC, KobayashiYoh commented on lib/ui_components/article_list_view.dart
> +        );
OKです。

2023-08-16 12:20 UTC, KobayashiYoh commented
修正お疲れ様です。
あと、state（https://github.com/shinonome-inc/qiita_client_yukiy/pull/19#discussion_r1295808133）だけ修正お願いします。
もう少しなので頑張っていきましょう🔥

2023-08-17 03:58 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +    final String? state = uri.queryParameters["state"];
stateをenvファイルに追加し、そこから参照するようにコードを変更したところ、下記画像の通り、修正できました！[stateをenvファイルに追加](https://github.com/shinonome-inc/qiita_client_yukiy/pull/19/commits/a30595cf2517b5b71a8bb6212674f750313486fa)
<img width="983" alt="スクリーンショット 2023-08-17 12 55 38" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/7dd53119-e180-4666-8a83-e81c5a6f02f4">

2023-08-19 00:58 UTC, KobayashiYoh approved these changes

2023-08-19 00:58 UTC, KobayashiYoh commented
2次レビューLGTMです🙌

2023-08-22 09:54 UTC, KobayashiYoh commented
コンフリクト解消後にビルドしてみましたか？
僕の環境だとビルド成功できないです😢

2023-09-02 01:37 UTC, Yuki0316 commented
ビルドに成功しましたので、記録を残しておきます。

rm -rf ios
flutter create ios
cd ios
pod install
cd ../
flutter run -d iPhone\ SE        ←スペースの前にoption+¥で\を入れる

ただ、あらためて見返してみると、なぜか自分のファイルからenvファイルが消えていたことが原因のような気もします。envファイルを改めてダウンロードし、yamlのassetsに追加したところ、綺麗さっぱりエラーがなくなりました。

2023-09-13 02:27 UTC, Yuki0316 commented
コンフリクト解消できました！Dawnにて教えていただきありがとうございました🧎‍♀️

2023-09-13 02:28 UTC, merged

2023-09-13 02:31 UTC, KobayashiYoh commented
長期間の実装・修正お疲れ様でした🍵