[Flutter最終課題] 設定画面 ・UI実装 ・利用規約・プライバシーポリシー
shinonome-inc/qiita_client_yukiy pull request #21
Opened 2023-08-16 03:09 UTC by Yuki0316

## 概要
設定画面のUI実装及び、利用規約とプライバシーポリシーページの作成、アプリバージョンの設置を行いました。
ログアウト機能に関しましては、まだ実装していません。
お手隙の際にご確認よろしくお願い致します。

## 実装した内容
設定画面
- UI作成
- 利用規約のモーダル
- プライバシーポリシーのモーダル
- アプリバージョンの取得、設置

## UI
<img src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/a4523757-7b8a-4502-beb8-fe7a9c364248" width="300">

## 動作確認
https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/820a009f-1ed3-40f7-9f2a-7937be6cf961

## 参考
[【Flutter】アプリバージョンを表示する
](https://qiita.com/kitaji12/items/833f08c9bab0c5c99f84)
[[Flutter]Containerにタップ処理を追加するには？
](https://www.choge-blog.com/programming/fluttercontainerontap/)

## その他

2023-08-17 00:36 UTC, KobayashiYoh commented
クライアントIDとクライアントシークレットは毎回プルリクに記載しておいた方がいいかもです（レビュワーが毎回変わるので）

2023-08-17 01:01 UTC, KobayashiYoh requested changes
4点コメントしました。

2023-08-17 01:01 UTC, KobayashiYoh commented on lib/constants/pribacy_policy.dart
> +  const PrivacyPolicy({Key? key}) : super(key: key);
プライバシーポリシーも利用規約も同じUIなのでUIコンポーネントを作って再利用するのが一般的な気がします。
修正は任意です。

2023-08-17 01:01 UTC, KobayashiYoh commented on lib/constants/pribacy_policy.dart
> +                          '''),
文字列があまりにも長すぎるので、定数クラスを作成してそこに定義した方がいいかもしれないですね。
修正任意です。

2023-08-17 01:01 UTC, KobayashiYoh commented on lib/pages/settings_page.dart
> +      children: [
以前もお伝えさせていただきましたが、RowやColumnは複数の要素を並べるためのウィジェットです。
要素が1つしかない場合は、RowやColumnの使用は避けましょう。

公式ドキュメントにも同じことが書かれています。
https://api.flutter.dev/flutter/widgets/Row-class.html

修正は任意です。

2023-08-17 01:01 UTC, KobayashiYoh commented on lib/ui_components/variable_height_list_tile.dart
> +                    const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
ここってboldですか？
もう一度figmaを確認してみてください。

<img src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/82624334/9e588a41-e904-49ca-99a1-7bc4b82f0fbc" width="300">

2023-08-18 01:11 UTC, Yuki0316 commented on lib/constants/pribacy_policy.dart
> +  const PrivacyPolicy({Key? key}) : super(key: key);
UIコンポーネントを作成し、再利用するよう変更しました！[UIコンポーネントと定数クラスの作成](https://github.com/shinonome-inc/qiita_client_yukiy/pull/21/commits/8d1f2596921e18b463ba637ba11410566b15e38e)

2023-08-18 01:12 UTC, Yuki0316 commented on lib/constants/pribacy_policy.dart
> +                          '''),
定数クラスを作成し、そこから引用するよう変更しました！そこで不要になったdartファイルも同時に削除しました！[UIコンポーネントと定数クラスの作成](https://github.com/shinonome-inc/qiita_client_yukiy/pull/21/commits/8d1f2596921e18b463ba637ba11410566b15e38e)

2023-08-18 01:13 UTC, Yuki0316 commented on lib/pages/settings_page.dart
> +      children: [
要素が一つしかなかったため、Alignment.centerLeftに変更しました！
[RowからAlignment.centerLeftに変更](https://github.com/shinonome-inc/qiita_client_yukiy/pull/21/commits/c4717793f0b34c9842e87fb1a79197210a7a73cf)

2023-08-18 01:14 UTC, Yuki0316 commented on lib/ui_components/variable_height_list_tile.dart
> +                    const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
figmaを確認したところ、「太さ：500」と設定されていたので、fontWeightをboldから、w500に変更しました！[fontWeightをw500に変更](https://github.com/shinonome-inc/qiita_client_yukiy/pull/21/commits/a12944aa8e89620cf89560da9a745b69faaefa07)

2023-08-19 00:20 UTC, KobayashiYoh approved these changes
コメントしました。
修正は任意です。

2023-08-19 00:20 UTC, KobayashiYoh commented on lib/pages/settings_page/modal_text.dart
> +  static const String privacyPolicy = '''プライバシーポリシー
今までpagesやui_componentsで機能ごとに分けられていたと思うのですが、急にディレクトリ構造を変えたのはどうしてですか？
統一した方が見やすいと思います。

2023-08-19 00:20 UTC, KobayashiYoh commented on lib/pages/settings_page/settings_page.dart
> +      margin: const EdgeInsets.only(top: 32, bottom: 8, left: 16),
👍

2023-08-19 00:21 UTC, KobayashiYoh commented on lib/ui_components/variable_height_list_tile.dart
> +                    const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
OKです。

2023-08-19 00:21 UTC, KobayashiYoh commented on lib/pages/settings_page.dart
> +      children: [
OKです。

2023-08-19 00:21 UTC, KobayashiYoh commented on lib/constants/pribacy_policy.dart
> +  const PrivacyPolicy({Key? key}) : super(key: key);
OKです。

2023-08-19 00:31 UTC, Yuki0316 commented on lib/pages/settings_page/modal_text.dart
> +  static const String privacyPolicy = '''プライバシーポリシー
ディレクトリ構造を元に戻しました！[e8f995b](https://github.com/shinonome-inc/qiita_client_yukiy/pull/21/commits/e8f995b18b4445f7bea0ddf8c16467d2a55a933e)

2023-08-19 00:41 UTC, ShuheiYoshidaJP reviewed
コメントしました！

2023-08-19 00:41 UTC, ShuheiYoshidaJP commented on lib/ui_components/variable_height_list_tile.dart
> +    return GestureDetector(
https://github.com/shinonome-inc/qiita_client_yukiy/blob/e8f995b18b4445f7bea0ddf8c16467d2a55a933e/lib/pages/settings_page.dart#L130-L133

今後の実装でここのログアウト機能が必要になると思われます。
なのでGestureDetectorを使っているのならば、今後の実装を考慮してonTapメソッド追加した方がいいかなと思います。

2023-08-19 01:04 UTC, Yuki0316 commented on lib/ui_components/variable_height_list_tile.dart
> +    return GestureDetector(
onTapメソッドの追加を行いました！[aec4348](https://github.com/shinonome-inc/qiita_client_yukiy/pull/21/commits/aec43488bf67adc10d32a3fc686b79aa8212acf5)

2023-08-19 02:12 UTC, ShuheiYoshidaJP commented
オッケーです。マージします。

2023-08-19 02:12 UTC, merged