[Flutter最終課題]Feature/my fix
shinonome-inc/qiita_client_yukiy pull request #24
Opened 2023-09-05 01:18 UTC by Yuki0316

## 概要
### 最終テストに移る前に気になった箇所を個人的に修正しまとめています。

## CLIENT_IDとCLIENT_SECRET
https://drive.google.com/drive/folders/1VCIxGsXi2GFxFAxsP5GyNvWNnzs36C17
プロジェクト直下に配置してください。
<img width="250" alt="スクリーンショット 2023-07-08 10 54 45" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/102783724/dd6b779f-8342-4259-b157-15723db82734">

## 実装した内容
- iPhone SEでビルドした際にTopPageのレイアウトが崩れていたので、端末サイズに関わらずレイアウトが同じになるよう変更
- FeedPage内で検索をした際、スクロールと同時にキーボードが下に隠れるよう変更
- SearchBarにclearボタンを追加
- 検索結果がなかった際に、表示させるページを追加。（ただ、最初のローディング時にもNoSearchResultが表示されてしまうので、CircleProgressIndicatorが出るように変更する必要あり）

## UI

## 動作確認

## 参考

## その他

2023-10-05 09:18 UTC, iu-yusei commented on lib/main.dart
> +      debugShowCheckedModeBanner: false,
falseに設定すると、Android特有の右上のdebugbannerを消せるんですね！
勉強になりました！

https://cbtdev.net/flutter-debug-banner/

2023-10-05 09:18 UTC, iu-yusei commented on lib/pages/feed_page.dart
> +  bool isNetworkError = false;
変数名の付け方がGOOD👍です！
一目で何の値が入っているかわかります！

2023-10-05 11:24 UTC, iu-yusei requested changes
最終課題、お疲れ様です！

１〜１１まで動作確認を行いました！
**9. ErrorPageのレイアウト修正** の部分だけ再確認してみてください！

### 動作確認結果

⭕️→正常に動作しています
⚠️→再確認してください

1. TopPageのレイアウト変更
→⭕️


2. スクロールでキーボードをClose
→⭕️

3. 削除ボタンの追加
→⭕️


4. 検索結果がなかった際の遷移
→⭕️


5. 検索結果がなかった際の遷移2
→⭕️


6. PullToRefresh(FeedPage)
→⭕️

7. PullToRefresh(TagPage)
→⭕️


8. PullToRefresh(UserPage), Dividerの設定
→⭕️

9. ErrorPageのレイアウト修正
→⚠️

   下記画像のように、Feedページや、Tagページで、検索バーやページタイトルが表示されていますが、figmaのモックアップでは、これらの要素は配置されていないので、修正が必要かもしれません。

    https://www.figma.com/file/r22atGeJ5LpGwOUbYXXOPw/Mobile-Qiita-App?type=design&node-id=10008-28718&mode=design&t=6OTE6lZbx8c2Nyq3-0

    `現状`
    <img width="320" alt="Pasted Graphic 1" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/78660150/63799030-b0df-4535-ba1f-749a1dc21419">

    `figma`
    <img width="320" alt="Pasted Graphic 2" src="https://github.com/shinonome-inc/qiita_client_yukiy/assets/78660150/cfd21d3c-f2cf-4244-afb5-2670f334276c">


10. FetchTagの修正
→⭕️


11. Overflowエラーの修正
→⭕️

2023-10-06 11:38 UTC, Yuki0316 commented
ErrorPageが表示される際に、figmaには設定されていない箇所を表示させないよう修正しました！
[ErrorPageをFigma通りに修正](https://github.com/shinonome-inc/qiita_client_yukiy/pull/24/commits/828b378acaefc29e0e09553542d1d0fafcb017cb)

2023-10-06 13:09 UTC, na7ei commented
動作確認しました！
LGTMです！

2023-10-08 00:35 UTC, Yoshida-koshi reviewed
コメントしました〜

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/pages/error_page.dart
> +        textField: TextField(),
error_pageのheaderにTextFieldは要らないと思います！

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/pages/feed_page.dart
> +      showNoSearchResult = newArticle.isEmpty ? true : false;
pageNumberが1の時のみこの行は実行したいと思うのですが、今のままだとpageNumberが2以上の時も実行されるので、無限スクロール中に検索0件のページに遷移されてしまう可能性もあると思ったのですが、いかがでしょうか？

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/pages/tag_detail_list_page.dart
> +      showError = newTagDetail.isEmpty ? true : false;
pageNumberが1の時は正常に記事が表示されて、2の時はAPIのリクエストは正常にできたけど、記事がない場合はerrorですか？

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/pages/tag_page.dart
> +      showError = newTags.isEmpty ? true : false;
ここも同じですね！

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/pages/user_page.dart
> +      showError = newArticle.isEmpty ? true : false;
ここも同じですね。

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/services/qiita_client.dart
> +  }
この関数はどこで使ってますか？

2023-10-08 00:35 UTC, Yoshida-koshi commented on lib/ui_components/no_search_result.dart
> +    return ListView(
なぜListViewにしたのでしょうか？個人的にはColumnでもいいと思いました！

2023-10-08 00:35 UTC, Yoshida-koshi commented
動作の方は問題ありません！

2023-10-08 01:33 UTC, Yuki0316 commented on lib/pages/error_page.dart
> +        textField: TextField(),
TextFieldをnull許容型にして、不要な箇所を全て削除しました！

2023-10-08 01:34 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +  }
他の場所で使用されていなかったので削除しました！

2023-10-08 01:58 UTC, Yuki0316 commented on lib/pages/tag_detail_list_page.dart
> +      showError = newTagDetail.isEmpty ? true : false;
修正しました！
[73424ea](https://github.com/shinonome-inc/qiita_client_yukiy/pull/24/commits/73424ea3fc1e796e9c13b1c9ebac2f3ed4efc7e9)

2023-10-08 01:58 UTC, Yuki0316 commented on lib/pages/tag_page.dart
> +      showError = newTags.isEmpty ? true : false;
修正しました！
[73424ea](https://github.com/shinonome-inc/qiita_client_yukiy/pull/24/commits/73424ea3fc1e796e9c13b1c9ebac2f3ed4efc7e9)

2023-10-08 01:58 UTC, Yuki0316 commented on lib/pages/user_page.dart
> +      showError = newArticle.isEmpty ? true : false;
修正しました！
[73424ea](https://github.com/shinonome-inc/qiita_client_yukiy/pull/24/commits/73424ea3fc1e796e9c13b1c9ebac2f3ed4efc7e9)

2023-10-08 02:00 UTC, Yuki0316 commented on lib/ui_components/no_search_result.dart
> +    return ListView(
Columnだとリフレッシュの際にスクロールができなかったので、ListViewに設定しました！

2023-10-08 02:00 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +      showNoSearchResult = newArticle.isEmpty ? true : false;
修正しました！
[73424ea](https://github.com/shinonome-inc/qiita_client_yukiy/pull/24/commits/73424ea3fc1e796e9c13b1c9ebac2f3ed4efc7e9)

2023-10-08 02:07 UTC, Yoshida-koshi commented
まだTextField完全に消せてないですね！

https://github.com/shinonome-inc/qiita_client_yukiy/blob/72acfdfee08503a780709c6f440a3820aeaa4838/lib/pages/user_not_login_page.dart#L18

2023-10-08 02:10 UTC, Yuki0316 commented
TextFieldの修正漏れがあったので修正しました！
[524fac0](https://github.com/shinonome-inc/qiita_client_yukiy/pull/24/commits/524fac0dea7b21fb4ef7a4f2e9790176b728d486)

2023-10-08 02:11 UTC, Yoshida-koshi commented
LGTMです！マージします！

2023-10-08 02:11 UTC, merged