Feature/article data
shinonome-inc/qiita_client_yukiy pull request #3
Opened 2022-12-18 03:29 UTC by Yuki0316

# FeedPageの記事一覧表示までを作成しました。
-APIの取得
-記事を画面に表示
-ID、投稿日、いいね数の表示
を行いました。

お手隙の際にご確認よろしくお願いします。

#参考になった記事
-[https://docs.flutter.dev/cookbook/networking/background-parsing#1-add-the-http-package](url)
-https://docs-flutter-dev.translate.goog/cookbook/networking/fetch-data?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=sc
-[https://isub.co.jp/flutter/flutter-http-api/#create-project](url)
-https://note.com/hatchoutschool/n/n647496ec4df5
-[https://pub.dev/packages/intl/install](url)
-[https://qiita.com/api/v2/docs#%E6%8A%95%E7%A8%BF](url)
-[https://api.flutter.dev/flutter/widgets/ListView-class.html](url)

#画像
![Simulator Screen Shot - iPhone 14 - 2022-12-18 at 12 17 43](https://user-images.githubusercontent.com/102783724/208279939-73da62d1-d3da-404e-90d9-c0273f14f367.png)

2022-12-18 03:51 UTC, Yoshida-koshi reviewed
コメントしました〜
多いと思いますが、何か分からないことがあったら聞いてください！

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/main.dart
> +    items: [],
このitemsはなぜ入れたのですか？

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/pages/feed_page.dart
> +            title: Text(article.title),
Figmaにタイトルは最大2行までなので、2行で入らなかった場合はFigmaの通りに実装してみてください。
| Figma | 現状 |
| --------- | --------- | 
| <img src="https://user-images.githubusercontent.com/85224998/208280239-7abecdac-8c65-402f-a3c1-77e28b1a9bee.png" width="300"> | <img src="https://user-images.githubusercontent.com/85224998/208280252-631536e0-c94f-498b-904c-166d84fc03df.png" width="300"> |

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/models/created.dart
> +class Created {}
このcreatedは何のために書いたのですか？

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/pages/feed_page.dart
> +                '@${article.user.id} 投稿日:${DateFormat('yyyy/MM/dd').format(DateTime.parse(article.dateTime))} いいね:${article.likesCount}'));
投稿日に入れている値が長すぎてパッと見何を書いているのか分からないので、変数で切り出してあげるといいと思います。

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/services/qiita_client.dart
> +      return jsonArray.map((json) => Article.fromJson(json)).toList();
これもパッと見何を返しているのか分からないので、変数で切り出してあげるといいと思います。

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/ui_components/search_bar.dart
> +class SearchBar extends StatelessWidget implements PreferredSizeWidget {
appBarを共通化しているのは素晴らしいですね！

2022-12-18 03:51 UTC, Yoshida-koshi commented on lib/ui_components/search_bar.dart
> +        'Feed',
このテキストも他クラスから渡された値を使って、表示すればいいと思うのですがいかがでしょうか？

2022-12-18 03:58 UTC, Yuki0316 commented on lib/main.dart
> +    items: [],
以前行っていた何かしらの残骸が残っており、放置してしまっていましたので削除しておきました。

2022-12-18 05:22 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +            title: Text(article.title),
タイトルをmaxLinesを用いて2行に設定、overflowを用いて語尾に3点リーダーを表示させるよう変更しました。

2022-12-18 05:24 UTC, Yuki0316 commented on lib/models/created.dart
> +class Created {}
勘違いで作ってしまったので、削除しておきました。

2022-12-18 06:38 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +                '@${article.user.id} 投稿日:${DateFormat('yyyy/MM/dd').format(DateTime.parse(article.dateTime))} いいね:${article.likesCount}'));
subtitleが長すぎたので、変数で切り出し見やすくしました。

2022-12-18 06:50 UTC, Yuki0316 commented on lib/services/qiita_client.dart
> +      return jsonArray.map((json) => Article.fromJson(json)).toList();
13行めのreturn文を変数を用いて見やすく変更しました。

2022-12-18 06:51 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +class SearchBar extends StatelessWidget implements PreferredSizeWidget {
ありがとうございます！

2022-12-18 07:01 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +        'Feed',
search_barの不要な変数（Searchは一箇所しかないため）を削除しました。

2022-12-18 07:06 UTC, Yoshida-koshi commented on lib/main.dart
> +    items: [],
OKです！

2022-12-18 07:08 UTC, Yoshida-koshi commented on lib/pages/feed_page.dart
> +            title: Text(article.title),
OKです！

2022-12-18 07:09 UTC, Yoshida-koshi commented on lib/models/created.dart
> +class Created {}
OKです！

2022-12-18 07:10 UTC, Yoshida-koshi commented on lib/pages/feed_page.dart
> +                '@${article.user.id} 投稿日:${DateFormat('yyyy/MM/dd').format(DateTime.parse(article.dateTime))} いいね:${article.likesCount}'));
OKです！

2022-12-18 07:11 UTC, Yoshida-koshi commented on lib/services/qiita_client.dart
> +      return jsonArray.map((json) => Article.fromJson(json)).toList();
OKです！

2022-12-18 07:16 UTC, Yoshida-koshi commented on lib/ui_components/search_bar.dart
> +        'Feed',
FeedPageと他のページの違いはSearchBarがあるかどうかなので、他クラスから値渡しをすることでFeedPageの時だけSearchBarを表示して、それ以外の時は表示しないようにすればいいと思います。

2022-12-18 08:40 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +        'Feed',
boolを用いて、FeedPageの時のみSearchbarが出現するように変更しました。FeedPage以外でのAppBarの高さも変更しました。

2022-12-18 09:00 UTC, Yoshida-koshi commented on lib/ui_components/search_bar.dart
> +        'Feed',
https://github.com/shinonome-inc/qiita_client_yukiy/blob/a31c718c2858ae2e94424fbfa38c58eb6d80d81e/lib/ui_components/upper_bar.dart#L18-L24
↑について、UpperAppはFeedPage以外にも使われるので、'Feed'は他クラスからこのFeedをもらって表示するようにしたほうがいいと思います。

2022-12-22 06:26 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +        'Feed',
AppBarの文字部分を"upper_name.dart"を作りインスタンス化してupper_bar.dartに組み込みました！ご確認の程よろしくお願いします。

2022-12-22 07:13 UTC, yoskoshi commented on lib/ui_components/search_bar.dart
> +        'Feed',
upper_bar.dartに他クラスからの値渡しの変数として、appBarTextみたいなのを用意して、appBarのtitleにこの変数を使って表示すればupper_name.dartは要らない気がするのですが、いかがでしょうか？

2022-12-22 07:21 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +        'Feed',
upper_name.dartの中のコードをそのままupper_bar.dartにペーストしてみたところ特にエラーも出なかったのですが、これで問題ないでしょうか？？
ご確認お願いします。

2022-12-22 07:39 UTC, yoskoshi commented on lib/ui_components/search_bar.dart
> +        'Feed',
これだとupper_bar.dartがFeedPage専用のappBarになってしまうので、UpperBarクラスの引数としてappBarのtitleであるappBarTextみたいな変数を用意して、FeedPageで'Feed'を指定してあげればいいと思います。そうすれば、TagPageでは'Tag'を指定すればUpperBarクラスでTagPageのappBarも作成できると思います。あと、このような方法を取るとUpperNameクラスは要らないと思います。

2022-12-22 13:58 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +        'Feed',
修正しました！ご確認お願いします。

2022-12-22 13:59 UTC, yoskoshi commented on lib/ui_components/search_bar.dart
> +        'Feed',
OKです！

2022-12-22 13:59 UTC, yoskoshi commented
LGTMなので、2次レビューを依頼してください！

2022-12-24 05:26 UTC, KobayashiYoh requested changes
コメントしました。
AppBarの戻るボタンだけは必ず修正お願いします。
それ以外は修正任意です。

2022-12-24 05:26 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +  const ArticleListPage({super.key});
本当にFeedPageクラスとArticleListPageクラスに分ける必要があるのか考えてみるといいかもしれませんね。

2022-12-24 05:26 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +  final List<Article> articles;
このクラスは別の画面でも使用できるので、別ファイルに定義した方がいいのかなと思いました。

2022-12-24 05:26 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +            ),
画像をキャッシュ化できるpackageがあるので紹介だけしておきます。
https://pub.dev/packages/cached_network_image

2022-12-24 05:26 UTC, KobayashiYoh commented on lib/ui_components/search_bar.dart
> +  const SearchBar({Key? key}) : super(key: key);
背景と同じ白色で見えづらいのですが、AppBarの戻るボタンが残っちゃっているので削除しておきましょう。
<img width="350" alt="スクリーンショット 2022-12-24 14 00 11" src="https://user-images.githubusercontent.com/82624334/209422783-e4e33da2-4500-4f38-a315-8d556e25fa10.png">

2022-12-24 05:46 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +  final List<Article> articles;
修正しました！

2022-12-24 05:46 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +  const ArticleListPage({super.key});
修正しました！

2022-12-24 05:47 UTC, Yuki0316 commented on lib/ui_components/search_bar.dart
> +  const SearchBar({Key? key}) : super(key: key);
修正しました！

2022-12-24 06:24 UTC, Yuki0316 commented on lib/pages/feed_page.dart
> +            ),
CachedNetworkImageを用いて画像をキャッシュ化しました！

2022-12-24 06:32 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +            ),
キャッシュ化だけでなく、エラー処理も書かれていて素晴らしいです👍

2022-12-24 06:33 UTC, KobayashiYoh approved these changes

2022-12-24 06:34 UTC, merged