Flutter
shinonome-inc/qiita_client_yukiy pull request #5
Opened 2023-02-03 06:55 UTC by Yuki0316

2023-02-03 08:01 UTC, Yoshida-koshi reviewed
コメントしました〜

2023-02-03 08:01 UTC, Yoshida-koshi commented on lib/services/web_view_screen.dart
> +          .evaluateJavascript("document.documentElement.scrollHeight;"),
AndroidStudioで横棒が上に重なっているメソッドを使うのは避けた方がいいと思います

2023-02-03 08:01 UTC, Yoshida-koshi commented on lib/ui_components/article_list_view.dart
> +    print('height: $_deviceHeight');
print文はいらないですね！

2023-02-03 08:01 UTC, Yoshida-koshi commented on pubspec.yaml
> +  modal_bottom_sheet: ^2.1.2
このパッケージどこかで使いましたか？？

2023-02-03 08:01 UTC, Yoshida-koshi commented on lib/ui_components/article_list_view.dart
> +                  height: _deviceHeight! * 0.9,
しっかりとデバイスの高さを参照できていて素晴らしいですね！！

2023-02-04 05:03 UTC, Yuki0316 commented on lib/services/web_view_screen.dart
> +          .evaluateJavascript("document.documentElement.scrollHeight;"),
文字の中央に取り消し線が入っている「evaluateJavascript」を「runJavascriptReturningResult」に変更しました。

2023-02-04 05:03 UTC, Yuki0316 commented on lib/ui_components/article_list_view.dart
> +    print('height: $_deviceHeight');
余分なprint文を削除しました。

2023-02-04 05:03 UTC, Yuki0316 commented on pubspec.yaml
> +  modal_bottom_sheet: ^2.1.2
パッケージを消しても何の問題もありませんでした！

2023-02-04 06:42 UTC, Yoshida-koshi commented
git pushできてないですね

2023-02-04 06:50 UTC, Yoshida-koshi commented on lib/services/web_view_screen.dart
> +          .evaluateJavascript("document.documentElement.scrollHeight;"),
OKです！

2023-02-04 06:51 UTC, Yoshida-koshi commented on lib/ui_components/article_list_view.dart
> +    print('height: $_deviceHeight');
OKです！

2023-02-04 06:51 UTC, Yoshida-koshi commented on pubspec.yaml
> +  modal_bottom_sheet: ^2.1.2
OKです！

2023-02-04 06:52 UTC, Yoshida-koshi commented
LGTMです！
2次レビューをお願いしてください！

2023-02-04 07:09 UTC, kota78 commented on lib/ui_components/article_list_view.dart
> +    print('height: $_deviceHeight');
ちなみにdebugPrintを使うと右上の緑三角（警告？）が消えたりします。

2023-02-04 07:16 UTC, KobayashiYoh approved these changes
コメントしました。
修正は任意です。

2023-02-04 07:16 UTC, KobayashiYoh commented on lib/services/web_view_screen.dart
> +  late String article;
この`article`という変数はどこかで使用していますか？

2023-02-04 07:16 UTC, KobayashiYoh commented on lib/services/web_view_screen.dart
> +    }
👍

2023-02-04 07:16 UTC, KobayashiYoh commented on lib/services/web_view_screen.dart
> +  final String url;
WebViewScreenはUIに関するクラスなので、`web_view_screen.dart`は`lib/pages`や`lib/views`に配置した方が適切かと思われます。

2023-02-04 07:47 UTC, KobayashiYoh requested changes
追加でコメントしました。

2023-02-04 07:47 UTC, KobayashiYoh commented on lib/services/search-page.dart
> +}
不要なクラスは削除しましょう。

2023-02-04 07:47 UTC, KobayashiYoh commented on lib/services/web_view_screen.dart
> +>>>>>>> Stashed changes:lib/pages/web_view_screen.dart
コンフリクトが発生しているので修正お願いします。

2023-02-04 07:55 UTC, Yuki0316 commented on lib/services/search-page.dart
> +}
不要なクラスを削除しました。

2023-02-04 07:55 UTC, Yuki0316 commented on lib/services/web_view_screen.dart
> +>>>>>>> Stashed changes:lib/pages/web_view_screen.dart
コンフリクトの修正を行いました。

2023-02-04 07:56 UTC, KobayashiYoh approved these changes

2023-02-04 07:56 UTC, merged